server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate
    username: root
    password: Sinha@12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect